PUT http://localhost:5000/api/users/61a05218d2688ddaacac8304
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTA1MjE4ZDI2ODhkZGFhY2FjODMwNCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzgwMTMyOTIsImV4cCI6MTYzODI3MjQ5Mn0.nzRdv0euPGecjFSggEWDbzaflWmyjuZB4OkqNRfODrQ

{
    "username":"lyminhtri"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"vana",
    "password":"123123"
}

###
GET  http://localhost:5000/api/users/find/61a05218d2688ddaacac8304
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTIxZTJmMmU4YWFmYWRjZTkzMDMzYiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzODAxNDU2OCwiZXhwIjoxNjM4MjczNzY4fQ.vvmLPp0XiMjrJxr6ZxrylQR3wniuC29APXPnqQMOAfE

{
    "username":"lyminhtri"
}

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"nguyenvane",
    "email":"vane@gmail.com",
    "password":"123123"
}

###
GET  http://localhost:5000/api/users?new=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTIxZTJmMmU4YWFmYWRjZTkzMDMzYiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzODAxNDU2OCwiZXhwIjoxNjM4MjczNzY4fQ.vvmLPp0XiMjrJxr6ZxrylQR3wniuC29APXPnqQMOAfE

###
GET  http://localhost:5000/api/users/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTIxZTJmMmU4YWFmYWRjZTkzMDMzYiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzODAxNDU2OCwiZXhwIjoxNjM4MjczNzY4fQ.vvmLPp0XiMjrJxr6ZxrylQR3wniuC29APXPnqQMOAfE

###
POST  http://localhost:5000/api/products/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTIxZTJmMmU4YWFmYWRjZTkzMDMzYiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzODAxNDU2OCwiZXhwIjoxNjM4MjczNzY4fQ.vvmLPp0XiMjrJxr6ZxrylQR3wniuC29APXPnqQMOAfE

{
    "title":"T-Shirt nike",
    "description":"t shirt is good clothes",
    "img":"test",
    "categories":["t shirt","women"],
    "size":"S",
    "color":"red",
    "price":50
}

###
GET  http://localhost:5000/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTIxZTJmMmU4YWFmYWRjZTkzMDMzYiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzODMyMTI4MCwiZXhwIjoxNjM4NTgwNDgwfQ.LhKLebCGgcEDfNA1y9LiPOIjfZC_4dedhJV2WNeD5xQ

###
POST   http://localhost:5000/api/orders/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTA1MjE4ZDI2ODhkZGFhY2FjODMwNCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzgwNzIyMDgsImV4cCI6MTYzODMzMTQwOH0.bhxgQk4GdfTEH42t6IhAbfC-TixYOSSPE1Rm19Ids50

{
    "userId":"61a05218d2688ddaacac8304",
    "products":[
        {
            "productId":"61a2eab9df63ca69f6276bd6",
            "quantity":2
        },
        {
            "productId":"61a2edd4781dfbcda6be6908",
            "quantity":1
        }
    ],
    "amount":50,
    "address":"HCM"
}

###
GET  http://localhost:5000/api/orders/income?pid=61a2edd4781dfbcda6be6908
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTIxZTJmMmU4YWFmYWRjZTkzMDMzYiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzODMyMTI4MCwiZXhwIjoxNjM4NTgwNDgwfQ.LhKLebCGgcEDfNA1y9LiPOIjfZC_4dedhJV2WNeD5xQ

###
PUT  http://localhost:5000/api/products/61a3439552c4aeb5f94fbc88
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTIxZTJmMmU4YWFmYWRjZTkzMDMzYiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzODAxNDU2OCwiZXhwIjoxNjM4MjczNzY4fQ.vvmLPp0XiMjrJxr6ZxrylQR3wniuC29APXPnqQMOAfE

{
    "price":66
}

###
DELETE   http://localhost:5000/api/products/61a4fd7f38ad199137c9c467
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTIxZTJmMmU4YWFmYWRjZTkzMDMzYiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzODMyMTI4MCwiZXhwIjoxNjM4NTgwNDgwfQ.LhKLebCGgcEDfNA1y9LiPOIjfZC_4dedhJV2WNeD5xQ

###
PUT   http://localhost:5000/api/users/61a5b36fe1eeaba536dbdc6b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTIxZTJmMmU4YWFmYWRjZTkzMDMzYiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzODMyMTI4MCwiZXhwIjoxNjM4NTgwNDgwfQ.LhKLebCGgcEDfNA1y9LiPOIjfZC_4dedhJV2WNeD5xQ

{
    "email":"nguyenvana123@gmail.com"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"nguyenvana",
    "password":"123123"
}

###
GET  http://localhost:5000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTIxZTJmMmU4YWFmYWRjZTkzMDMzYiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzODMyMTI4MCwiZXhwIjoxNjM4NTgwNDgwfQ.LhKLebCGgcEDfNA1y9LiPOIjfZC_4dedhJV2WNeD5xQ

###
POST  http://localhost:5000/api/carts/addtocart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTU4NDlhZjcyMmM4ZTY3ZjY4NDM0ZCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzg0MzkwNjUsImV4cCI6MTYzODY5ODI2NX0.xXl5XfSKCtY7K33QFUDj0M6ggzanMMe1Wuj5dj95q1o

{
    "cartItems":[
            {
                "product":"61a2edd4781dfbcda6be6908",
            "quantity":3,
            "size": "M",
        "color":"White"
            }
    ]   
}

###
GET  http://localhost:5000/api/carts/getcartitems
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTU4NDlhZjcyMmM4ZTY3ZjY4NDM0ZCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzg0MzkwNjUsImV4cCI6MTYzODY5ODI2NX0.xXl5XfSKCtY7K33QFUDj0M6ggzanMMe1Wuj5dj95q1o

###
DELETE   http://localhost:5000/api/carts/removeitem
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTU4NDlhZjcyMmM4ZTY3ZjY4NDM0ZCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzg0MzkwNjUsImV4cCI6MTYzODY5ODI2NX0.xXl5XfSKCtY7K33QFUDj0M6ggzanMMe1Wuj5dj95q1o

{
    "productId":"61a2edd4781dfbcda6be6908",
            "size": "M",
        "color":"White"
}

###
POST   http://localhost:5000/api/carts/changequantity
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTU4NDlhZjcyMmM4ZTY3ZjY4NDM0ZCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzg0MzkwNjUsImV4cCI6MTYzODY5ODI2NX0.xXl5XfSKCtY7K33QFUDj0M6ggzanMMe1Wuj5dj95q1o

{
    "productId":"61a3438a52c4aeb5f94fbc87",
            "size": "M",
        "color":"Green",
        "value":-1
}

###
GET  http://localhost:5000/api/products